export const JWT_PUBLIC_KEY =
  process.env.JWT_PUBLICK_KEY ||
  `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq4uYs55B7XJMDD6MuVms
P2kDPwF+BFtD7gW7DvlwPck7IXneen+EYiCxTbGLih03mdh1hrMMt37Fdflj+9R7
Cfvf1RBJUZQcAnX+bNzZAQGBpECCKwlm6Tdf5wiHnJHLD6CHEkRZ2rYjT+vv1jfs
Z4BysYS0ByyWaCt3rFzuc8HBHpResOJkjxW7Skodt6elBetN3DlIJoTmPmzjdNIu
fACFxQDmiqP1sNKIVkRvPb7fk8EXL75A71YpFm7qDPhAqBb9oTY2Dqo6ueXRskSJ
aYS6yGgUXm1RqgGAcvaH9Up+APcwIzOGteGtiAZ7D4J0Drp1MAPK5hoWaS+ZyzoN
UwIDAQAB
-----END PUBLIC KEY-----
`;
